version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes: []
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://clinic.aspiratcm.com/api/v1

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres-clinic
    environment:
      - DB_HOST=postgres-clinic
      - DB_PORT=5432
      - DB_DATABASE=clinic
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

  postgres-clinic:
    image: postgres:15
    container_name: postgres-clinic
    environment:
      - POSTGRES_DB=clinic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
