"""add_herbs_and_tcm_settings_tables

Revision ID: 0c697ccff503
Revises: 94ddcc775540
Create Date: 2025-04-26 10:56:58.897140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c697ccff503'
down_revision: Union[str, None] = '94ddcc775540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('herbs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('concentration_ratio', sa.Float(), nullable=True),
    sa.Column('decoction_equivalent_per_g', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('quantity_per_bottle', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('is_compound', sa.Boolean(), nullable=True),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_herbs_code'), 'herbs', ['code'], unique=True)
    op.create_table('tcm_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False, comment='設定類別'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='代碼'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='名稱'),
    sa.Column('aliases', sa.Text(), nullable=True, comment='別名，以逗號分隔'),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tcm_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcm_settings_category'), 'tcm_settings', ['category'], unique=False)
    op.create_index(op.f('ix_tcm_settings_code'), 'tcm_settings', ['code'], unique=False)
    op.create_index(op.f('ix_tcm_settings_id'), 'tcm_settings', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('herb_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['herb_id'], ['herbs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('herb_items', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('herb_items', sa.Column('structured_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('herb_items', 'structured_data')
    op.drop_column('herb_items', 'source')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_tcm_settings_id'), table_name='tcm_settings')
    op.drop_index(op.f('ix_tcm_settings_code'), table_name='tcm_settings')
    op.drop_index(op.f('ix_tcm_settings_category'), table_name='tcm_settings')
    op.drop_table('tcm_settings')
    op.drop_index(op.f('ix_herbs_code'), table_name='herbs')
    op.drop_table('herbs')
    # ### end Alembic commands ###
