"""add_patient_ai_fields

Revision ID: 990010ad9980
Revises: 542f8ed7f0ee
Create Date: 2025-04-09 02:41:00.926085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '990010ad9980'
down_revision: Union[str, None] = '542f8ed7f0ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('chief_complaint', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('health_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'health_profile')
    op.drop_column('patients', 'chief_complaint')
    op.drop_column('patients', 'note')
    # ### end Alembic commands ###
