"""trying_to_merge_three_core_function

Revision ID: bee911c4515c
Revises: 0c697ccff503
Create Date: 2025-04-27 14:23:51.577427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee911c4515c'
down_revision: Union[str, None] = '0c697ccff503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('referral_source', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('referral_notes', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('is_troublesome', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('is_contagious', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('special_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'special_note')
    op.drop_column('patients', 'is_contagious')
    op.drop_column('patients', 'is_troublesome')
    op.drop_column('appointments', 'referral_notes')
    op.drop_column('appointments', 'referral_source')
    # ### end Alembic commands ###
