"""add_structured_data_to_prescriptions_and_herb_items

Revision ID: bef231edfb1d
Revises: bee911c4515c
Create Date: 2025-04-29 21:10:03.558721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef231edfb1d'
down_revision: Union[str, None] = 'bee911c4515c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions', sa.Column('structured_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'structured_data')
    # ### end Alembic commands ###
