"""fix_add member_plan table

Revision ID: e40a2a201a61
Revises: 0a76feabd852
Create Date: 2025-05-09 23:18:34.676975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40a2a201a61'
down_revision: Union[str, None] = '0a76feabd852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('base_amount', sa.Float(), nullable=False),
        sa.Column('bonus_amount', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'),
        sa.Column('sort_order', sa.Integer(), nullable=True, server_default='0'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_plans_id'), 'member_plans', ['id'], unique=False)
    op.create_index(op.f('ix_member_plans_name'), 'member_plans', ['name'], unique=True)
    # ### end Alembic commands ###

    # 插入一些預設的增值計劃
    op.bulk_insert(
        sa.table(
            'member_plans',
            sa.column('name', sa.String),
            sa.column('description', sa.String),
            sa.column('base_amount', sa.Float),
            sa.column('bonus_amount', sa.Float),
            sa.column('is_active', sa.Boolean),
            sa.column('sort_order', sa.Integer)
        ),
        [
            {
                'name': '基本增值計劃',
                'description': '增值$1000獲贈$100',
                'base_amount': 1000.0,
                'bonus_amount': 100.0,
                'is_active': True,
                'sort_order': 1
            },
            {
                'name': '標準增值計劃',
                'description': '增值$2000獲贈$300',
                'base_amount': 2000.0,
                'bonus_amount': 300.0,
                'is_active': True,
                'sort_order': 2
            },
            {
                'name': '高級增值計劃',
                'description': '增值$5000獲贈$1000',
                'base_amount': 5000.0,
                'bonus_amount': 1000.0,
                'is_active': True,
                'sort_order': 3
            }
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_plans_name'), table_name='member_plans')
    op.drop_index(op.f('ix_member_plans_id'), table_name='member_plans')
    op.drop_table('member_plans')
    # ### end Alembic commands ### 
